```python
import openai
import os

class GPTModel:
    def __init__(self):
        self.api_key = os.getenv('OPENAI_API_KEY')
        self.model_name = 'text-davinci-003'  # GPT-3.5 model
        openai.api_key = self.api_key

    def generate_response(self, prompt):
        response = openai.Completion.create(
            engine=self.model_name,
            prompt=prompt,
            max_tokens=150
        )
        return response.choices[0].text.strip()

gpt_model = GPTModel()

def handle_question(question):
    return gpt_model.generate_response(question)
```
This Python script creates a class `GPTModel` that uses OpenAI's GPT-3.5 model to generate responses to prompts. The `handle_question` function takes a question as input and returns a response generated by the GPT model. The API key for OpenAI is fetched from the environment variables.